### ISSUE TITLE
punjabi unicode is adding undefined

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/anvaad-js#13]
undefined characters should be ignored in worst case.

best case, lets add replacements for those that are coming back undefined.

**Comment by ManjotS** [comment]
![image](https://user-images.githubusercontent.com/644885/36225121-8366863e-117e-11e8-8917-e4c512df07a4.png)

**Comment by navdeepsinghkhalsa** [comment]
Fixed in master
