### ISSUE TITLE
rahau becoming rahaa in english translit

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/anvaad-js#15]
i think its due to rule precedence

**Comment by Gauravjeetsingh** [comment]
@ManjotS Veerji! as you told in our call, this issue is fixed as well.
I tested ਰਹਾਉ using `anvaad.translit('rhwau')` and it became `rahaau` in english translit.

I feel it's safe to close this ticket as well then.

**Comment by tarunsingh5** [comment]
closing this ticket for now
