### ISSUE TITLE
English translation, tipee gets a before and after

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/anvaad-js#16]
Hirde jaap parmanand as example. Too many a in actual transliteration.

**Comment by Gauravjeetsingh** [comment]
As of now, Hirde jaap transliterates to 
`hiradhai jap paramaana(n)dh ||`

but the ideal transliteration should be following?
`hiradhai jap paramana(n)dh ||`

@ManjotS Can you please confirm if I got this right?

**Comment by ManjotS** [comment]
I must have  fixed this and  not closed the ticket.

I remember the issue was paramaanaa(n)adh
