### ISSUE TITLE
unicode doesn't cover all cases

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/anvaad-js#21]
see english translit to see a lit of minimum characters that should be covered.

**Comment by ManjotS** [comment]
ਖ਼ for example

**Comment by ManjotS** [comment]
all characters are in readme in master branch

**Comment by ManjotS** [comment]
also one way to figure out what we are missing is print out the characters we do convert and do sort on the command line then diff against the list in readme.

**Comment by navdeepsinghkhalsa** [comment]
Resolved by #25
