### ISSUE TITLE
add alphabetize function

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/anvaad-js#24]
should be a sort function that can alphabetize in gurmukhi (ignoring matras/vowels)

**Comment by ManjotS** [comment]
should work for font and for unicode

**Comment by tarunsingh5** [comment]
why would ignore matras?

**Comment by ManjotS** [comment]
Because matras are not including in alphabetizing. I in pothis such as
Amrit kirtan.. you ignore the sihari before a baba etc

**Comment by tarunsingh5** [comment]
matras actually are included in alphabetizing in pothis like Amrit Kirtan, Mahan Kosh, etc

**Comment by tarunsingh5** [comment]
closing this as it is merged
