### ISSUE TITLE
unicode test case causing sihari transposition

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/anvaad-js#28]
something is wrong in the conversion and test for:

ਨੁ ਜੋਗੁ ਕਉਨੁ ਗੵਾਨੁ ਧੵਾਨੁ ਕਵਨ ਬਿਧਿ ਉਸ੍ਤਤਿ ਕਰੀਐ

When copying and pasting to microsoft word, ustat's sihari is after the tatas

![screen shot 2018-08-08 at 10 12 30 am](https://user-images.githubusercontent.com/644885/43852997-981a0a0c-9af3-11e8-9f27-fb9a877ecb86.png)

**Comment by irvanjitsingh** [comment]
Can't reproduce, seems to be a font issue.
