### ISSUE TITLE
Issues in current devnagri transliteration

### ISSUE THREAD

**Issue by Gauravjeetsingh** [KhalisFoundation/anvaad-js#35]
I copied japji sahib from [sttm.co](https://www.sikhitothemax.org/sundar-gutka/2) and transliterated it to hindi using `anvaad.translit(..)` function.
Then used [this](http://www.croydongurdwara.co.uk/wp-content/uploads/2016/03/Nitnem-in-Devanagari-Uni.pdf) and [this](https://vedpuran.files.wordpress.com/2013/02/siri-guru-granth-sahib-in-hindi.pdf) to compare.

Found eight issues so far. Yellow words are from the above pdf and next to them is our transliterated version.
![compare](https://user-images.githubusercontent.com/1990932/52413085-8f91b580-2b06-11e9-9722-7dc38de34398.png)

Will be adding more issues as I find in this ticket.

**Comment by tarunsingh5** [comment]
#36 addresses
