### ISSUE TITLE
Ik-Oan-Kaar - Style is different now - Unicode Specific Issue

### ISSUE THREAD

**Issue by harpreetkhalsagtbit** [KhalisFoundation/anvaad-js#89]
**Describe the bug**
Unicode Ik-Oan-Kaar symbol is a little distorted now..

**To Reproduce**
1. Go to 'Any Bani with the Ik-Oan-Kaar symbol'
2. Click on 'Advance'
3. Change Font selection to Unicode

**Expected behavior**

**Screenshots**
![Screenshot 2020-08-19 at 12 12 47 PM](https://user-images.githubusercontent.com/2958292/90601128-4f3fe700-e215-11ea-901c-44a2f8254342.png)

**Comment by harpreetkhalsagtbit** [comment]
Yes, its browser specific. It's not a conversion issue. I have found the issue in
Chrome:v84
Safari: v13.1

Working fine with mozilla v78

**Comment by irvanjitsingh** [comment]
This issue needs to be reopened in sttm-web. The solution is to use the [Akaash Unicode font](https://gurbanifiles.net/unicode/index.htm). It will allow consistent rendering of Ik Oangkaar across different browsers and operating systems.

Although there's still a few issues with rendering some Gurmukhi character combinations on safari and older browsers when using Akaash, Ik Oangkaar is not one of them.

**Comment by irvanjitsingh** [comment]
Opened an issue under sttm-web, will close this.
